Sync state before linking
Still doesn't work, same error:
Error: Device '/dev/video0' is busy

I will probably need to block the source pad with a blocking pad probe,
wait that the probe callback is called, then link the pads, then unblock
the source pad.